In [19]:
import pandas as pd
autos = pd.read_json("../Data/autos.json")
autos

,aspiration,body-style,bore,city-mpg,compression-ratio,curb-weight,drive-wheels,engine-location,engine-size,engine-type,...,make,normalized-losses,num-of-cylinders,num-of-doors,peak-rpm,price,stroke,symboling,wheel-base,width
0,std,convertible,3.47,21,9.0,2548,rwd,front,130,dohc,...,alfa-romero,NaN,four,two,5000.0,13495.0,2.68,3,88.6,64.1
1,std,convertible,3.47,21,9.0,2548,rwd,front,130,dohc,...,alfa-romero,NaN,four,two,5000.0,16500.0,2.68,3,88.6,64.1
2,std,hatchback,2.68,19,9.0,2823,rwd,front,152,ohcv,...,alfa-romero,NaN,six,two,5000.0,16500.0,3.47,1,94.5,65.5
3,std,sedan,3.19,24,10.0,2337,fwd,front,109,ohc,...,audi,164.0,four,four,5500.0,13950.0,3.40,2,99.8,66.2
4,std,sedan,3.19,18,8.0,2824,4wd,front,136,ohc,...,audi,164.0,five,four,5500.0,17450.0,3.40,2,99.4,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,std,sedan,3.78,23,9.5,2952,rwd,front,141,ohc,...,volvo,95.0,four,four,5400.0,16845.0,3.15,-1,109.1,68.9
201,turbo,sedan,3.78,19,8.7,3049,rwd,front,141,ohc,...,volvo,95.0,four,four,5300.0,19045.0,3.15,-1,109.1,68.8
202,std,sedan,3.58,18,8.8,3012,rwd,front,173,ohcv,...,volvo,95.0,six,four,5500.0,21485.0,2.87,-1,109.1,68.9
203,turbo,sedan,3.01,26,23.0,3217,rwd,front,145,ohc,...,volvo,95.0,six,four,4800.0,22470.0,3.40,-1,109.1,68.9
204,turbo,sedan,3.78,19,9.5,3062,rwd,front,141,ohc,...,volvo,95.0,four,four,5400.0,22625.0,3.15,-1,109.1,68.9

In [27]:
jaguar_cars = autos[autos["make"] == "jaguar"]
autos.query("make == 'jaguar'")
jaguar_count = len(jaguar_cars)
most_expensive_jaguar_price = jaguar_cars['price'].max()

print(f"Number of Jaguar cars: {jaguar_count}")
print(f"Price of the most expensive Jaguar car: {most_expensive_jaguar_price:}")

Number of Jaguar cars: 3
Price of the most expensive Jaguar car: 36000.0

In [28]:
toyota_cars = autos[autos["make"] == "toyota"]
autos.query("make == 'toyota'")
toyota_count = len(toyota_cars)
most_expensive_toyota_price = toyota_cars["price"].max()
print(f"Number of Jaguar cars: {toyota_count}")
print(f"Price of the most expensive Jaguar car: {most_expensive_toyota_price:}")

Number of Jaguar cars: 32
Price of the most expensive Jaguar car: 17669.0

In [30]:
cars = autos[autos["make"] == ""]
most_expensive_car = ["make"].max()

AttributeError: 'list' object has no attribute 'max'