# Labbration covid-19
### Uppgift 1
Börja med att manuellt läsa Excel-filerna och de olika bladen i varje dokument. Använd därefter Pandas för
att läsa in bladet: "Veckodata Riket" i covid19-filen.

In [61]:
import pandas as pd

excel_file_path = 'Labb-data/Folkhalsomyndigheten_Covid19.xlsx'


df = pd.read_excel(excel_file_path, sheet_name=6)

df

,år,veckonummer,Region,Antal_fall_vecka,Kum_antal_fall,Antal_intensivvårdade_vecka,Kum_antal_intensivvårdade,Antal_avlidna_vecka,Kum_antal_avlidna,Antal_fall_100000inv_vecka,Kum_fall_100000inv
0,2020,1,Blekinge,0,0,0,0,0,0,0,0
1,2020,2,Blekinge,0,0,0,0,0,0,0,0
2,2020,3,Blekinge,0,0,0,0,0,0,0,0
3,2020,4,Blekinge,0,0,0,0,0,0,0,0
4,2020,5,Blekinge,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3082,2022,38,Östergötland,248,97976,1,437,5,871,53,20973
3083,2022,39,Östergötland,238,98214,2,439,7,878,51,21024
3084,2022,40,Östergötland,204,98418,0,439,3,881,44,21067
3085,2022,41,Östergötland,145,98563,1,440,4,885,31,21098
3086,2022,42,Östergötland,152,98715,0,440,4,889,33,21131

### Använder df.info och df.desribe för att få en snabb överblick 
- df.info: ger överblick av datatyper
- df.describe: ger statistisk sammanfattningar för numeriska kolumner

In [ ]:
print("Info:")
print(df.info())

print("\nDescribe:")
print(df.describe())

### Slå ihop kolumnerna "år" och "veckonummer" till en kolumn med namn "Vecka"

In [62]:
df["vecka"] = df.apply(lambda row: f"{row['år']}v{row['veckonummer']}", axis=1)
df

,år,veckonummer,Region,Antal_fall_vecka,Kum_antal_fall,Antal_intensivvårdade_vecka,Kum_antal_intensivvårdade,Antal_avlidna_vecka,Kum_antal_avlidna,Antal_fall_100000inv_vecka,Kum_fall_100000inv,vecka
0,2020,1,Blekinge,0,0,0,0,0,0,0,0,2020v1
1,2020,2,Blekinge,0,0,0,0,0,0,0,0,2020v2
2,2020,3,Blekinge,0,0,0,0,0,0,0,0,2020v3
3,2020,4,Blekinge,0,0,0,0,0,0,0,0,2020v4
4,2020,5,Blekinge,0,0,0,0,0,0,0,0,2020v5
...,...,...,...,...,...,...,...,...,...,...,...,...
3082,2022,38,Östergötland,248,97976,1,437,5,871,53,20973,2022v38
3083,2022,39,Östergötland,238,98214,2,439,7,878,51,21024,2022v39
3084,2022,40,Östergötland,204,98418,0,439,3,881,44,21067,2022v40
3085,2022,41,Östergötland,145,98563,1,440,4,885,31,21098,2022v41
3086,2022,42,Östergötland,152,98715,0,440,4,889,33,21131,2022v42